### ISSUE TITLE
Value in editor is not updated when model is modified

### ISSUE THREAD

**Issue by loicknuchel** [KillerCodeMonkey/ngQuill#2] opened 2014-12-09 13:47 UTC
Hi,

When I update the model linked to editor, the editor does not update.
You can try it by updated the model with a timout or link the model to the editor and a textarea.

**Comment by bengtweisse** [comment] 2015-01-09 18:26
because i do not get any answer in time.. i close the issue. you can reopen if you have any other problems related to this.

**Closed** 2015-01-09 18:27 UTC

**Comment by oracleruiz** [comment] 2015-07-14 18:12
Hi, 
Event tough the issue is closed, I had the same requirement as @loicknuchel had and my solution was to add the following code to *ng-quill.js* around line 197:
```javascript
//Update editor content when variable ngModel is updated in the parent controller.
$scope.$watch('ngModel',function (newValue, oldValue) {
    if (newValue != oldValue && (newValue != undefined)) {
        editor.setHTML(newValue);
    }
});
```

**Comment by pcsantana** [comment] 2016-05-16 17:33
Hi!
I tried to use the API methods to update programatically the editor content, but when I change the model to a empty string and use editor.setHtml to update the content, I got the error below:

`ionic.bundle.js:25642 Error: [$rootScope:inprog] $apply already in progress`

I resolved it problem by wrapping the code (line 306) inside `$timeout`:

```javascript
$timeout(function () {
    $scope.$apply(function () {
        // Calculate content length
        $scope.modelLength = editor.getLength();
        // Check if error class should be set
        if (oldChange) {
            setClass();
        }
        var setValue;
        if (config.save === 'text') {
            setValue = editor.getText();
        } else if (config.save === 'contents') {
            setValue = editor.getContents();
        } else {
            setValue = editor.getHTML();
        }
        // Set new model value
        if(editor.getLength() <= 1) {
            ngModel.$setViewValue('');
        } else {
            ngModel.$setViewValue(setValue);
        }
    });
});
```

Let me know if I am doing something wrong.
Thank you!

**Comment by KillerCodeMonkey** [comment] 2016-05-16 19:19
wrapping $timeout and $scope.$apply should not be done.

Could you show me, how you are using the API to set the value?

**Comment by pcsantana** [comment] 2016-05-16 21:21
I have a modal with ngquill.

```html
<div class="editor-wrapper">
    <ng-quill-editor data-tap-disabled="true" style="height:400px !important;" class="selectable" ng-model="vm.editorText" toolbar="true" toolbar-entries="size bold list bullet italic underline align color"></ng-quill-editor>
</div>
````

The first time when page is loaded, everything works well.
Scenario:
1. Open the modal;
2. Write some text in ngquill;
3. Save the doc 

But I need add more documents or edit the older one. So I open the modal again.

```javascript
function openAddModal(id) {
    
    //Clear the model.
    //If I set a white space (" ") instead a empty string, I don't need to use the API method (setHtml), because the editor updates!
    //I was using this workaround to clear the model and the editor, but I realized that when I paste some text with "Ctrl + V", the model does not update without typing anything.
    vm.editorText = ""; 
    
    //New doc
    if(id == null) {    
    	//Clear the editor.
    	//Here I got the error
        editor.setHTML('<div></div>'); 
        vm.modalNewDocument.show();
    } else { 
    	//get the document...
        vm.editorText = vm.document.content;
        vm.modalNewDocument.show();
    }
}
```

**Comment by KillerCodeMonkey** [comment] 2016-05-17 05:37
try to wrap only

`editor.setHTML('<div></div>');`

in $timeout

**Comment by pcsantana** [comment] 2016-05-17 12:23
Thank you!!!
It worked very well! :D
